version: "3.1"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    network_mode: host
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "node-app"
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
